/*
Copyright 2025 Millstone HQ.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccountInitParameters struct {

	// Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AccountObservation struct {

	// Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AccountParameters struct {

	// Identifier
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type MetaInitParameters struct {
}

type MetaObservation struct {

	// The zone is only configured for CDN.
	CdnOnly *bool `json:"cdnOnly,omitempty" tf:"cdn_only,omitempty"`

	// Number of Custom Certificates the zone can have.
	CustomCertificateQuota *float64 `json:"customCertificateQuota,omitempty" tf:"custom_certificate_quota,omitempty"`

	// The zone is only configured for DNS.
	DNSOnly *bool `json:"dnsOnly,omitempty" tf:"dns_only,omitempty"`

	// The zone is setup with Foundation DNS.
	FoundationDNS *bool `json:"foundationDns,omitempty" tf:"foundation_dns,omitempty"`

	// Number of Page Rules a zone can have.
	PageRuleQuota *float64 `json:"pageRuleQuota,omitempty" tf:"page_rule_quota,omitempty"`

	// The zone has been flagged for phishing.
	PhishingDetected *bool `json:"phishingDetected,omitempty" tf:"phishing_detected,omitempty"`

	Step *float64 `json:"step,omitempty" tf:"step,omitempty"`
}

type MetaParameters struct {
}

type OwnerInitParameters struct {
}

type OwnerObservation struct {

	// Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the owner.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The type of owner.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type OwnerParameters struct {
}

type PlanInitParameters struct {
}

type PlanObservation struct {

	// States if the subscription can be activated.
	CanSubscribe *bool `json:"canSubscribe,omitempty" tf:"can_subscribe,omitempty"`

	// The denomination of the customer.
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// If this Zone is managed by another company.
	ExternallyManaged *bool `json:"externallyManaged,omitempty" tf:"externally_managed,omitempty"`

	// How often the customer is billed.
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// States if the subscription active.
	IsSubscribed *bool `json:"isSubscribed,omitempty" tf:"is_subscribed,omitempty"`

	// If the legacy discount applies to this Zone.
	LegacyDiscount *bool `json:"legacyDiscount,omitempty" tf:"legacy_discount,omitempty"`

	// The legacy name of the plan.
	LegacyID *string `json:"legacyId,omitempty" tf:"legacy_id,omitempty"`

	// Name of the owner.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// How much the customer is paying.
	Price *float64 `json:"price,omitempty" tf:"price,omitempty"`
}

type PlanParameters struct {
}

type TenantInitParameters struct {
}

type TenantObservation struct {

	// Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the Tenant account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TenantParameters struct {
}

type TenantUnitInitParameters struct {
}

type TenantUnitObservation struct {

	// Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TenantUnitParameters struct {
}

type ZoneInitParameters struct {
	Account *AccountInitParameters `json:"account,omitempty" tf:"account,omitempty"`

	// The domain name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Indicates whether the zone is only using Cloudflare DNS services. A
	// true value means the zone will not receive security or performance
	// benefits.
	Paused *bool `json:"paused,omitempty" tf:"paused,omitempty"`

	// A full zone implies that DNS is hosted with Cloudflare. A partial zone is
	// typically a partner-hosted zone or a CNAME setup.
	// Available values: "full", "partial", "secondary", "internal".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// An array of domains used for custom name servers. This is only
	// available for Business and Enterprise plans.
	VanityNameServers []*string `json:"vanityNameServers,omitempty" tf:"vanity_name_servers,omitempty"`
}

type ZoneObservation struct {
	Account *AccountObservation `json:"account,omitempty" tf:"account,omitempty"`

	// The last time proof of ownership was detected and the zone was made
	// active.
	ActivatedOn *string `json:"activatedOn,omitempty" tf:"activated_on,omitempty"`

	// Allows the customer to use a custom apex.
	// *Tenants Only Configuration*.
	CnameSuffix *string `json:"cnameSuffix,omitempty" tf:"cname_suffix,omitempty"`

	// When the zone was created.
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// The interval (in seconds) from when development mode expires
	// (positive integer) or last expired (negative integer) for the
	// domain. If development mode has never been enabled, this value is 0.
	DevelopmentMode *float64 `json:"developmentMode,omitempty" tf:"development_mode,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Meta *MetaObservation `json:"meta,omitempty" tf:"meta,omitempty"`

	// When the zone was last modified.
	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	// The domain name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name servers Cloudflare assigns to a zone.
	NameServers []*string `json:"nameServers,omitempty" tf:"name_servers,omitempty"`

	// DNS host at the time of switching to Cloudflare.
	OriginalDnshost *string `json:"originalDnshost,omitempty" tf:"original_dnshost,omitempty"`

	// Original name servers before moving to Cloudflare.
	OriginalNameServers []*string `json:"originalNameServers,omitempty" tf:"original_name_servers,omitempty"`

	// Registrar for the domain at the time of switching to Cloudflare.
	OriginalRegistrar *string `json:"originalRegistrar,omitempty" tf:"original_registrar,omitempty"`

	Owner *OwnerObservation `json:"owner,omitempty" tf:"owner,omitempty"`

	// Indicates whether the zone is only using Cloudflare DNS services. A
	// true value means the zone will not receive security or performance
	// benefits.
	Paused *bool `json:"paused,omitempty" tf:"paused,omitempty"`

	// Legacy permissions based on legacy user membership information.
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	Plan *PlanObservation `json:"plan,omitempty" tf:"plan,omitempty"`

	// The zone status on Cloudflare.
	// Available values: "initializing", "pending", "active", "moved".
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	Tenant *TenantObservation `json:"tenant,omitempty" tf:"tenant,omitempty"`

	TenantUnit *TenantUnitObservation `json:"tenantUnit,omitempty" tf:"tenant_unit,omitempty"`

	// A full zone implies that DNS is hosted with Cloudflare. A partial zone is
	// typically a partner-hosted zone or a CNAME setup.
	// Available values: "full", "partial", "secondary", "internal".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// An array of domains used for custom name servers. This is only
	// available for Business and Enterprise plans.
	VanityNameServers []*string `json:"vanityNameServers,omitempty" tf:"vanity_name_servers,omitempty"`

	// Verification key for partial zone setup.
	VerificationKey *string `json:"verificationKey,omitempty" tf:"verification_key,omitempty"`
}

type ZoneParameters struct {

	// +kubebuilder:validation:Optional
	Account *AccountParameters `json:"account,omitempty" tf:"account,omitempty"`

	// The domain name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Indicates whether the zone is only using Cloudflare DNS services. A
	// true value means the zone will not receive security or performance
	// benefits.
	// +kubebuilder:validation:Optional
	Paused *bool `json:"paused,omitempty" tf:"paused,omitempty"`

	// A full zone implies that DNS is hosted with Cloudflare. A partial zone is
	// typically a partner-hosted zone or a CNAME setup.
	// Available values: "full", "partial", "secondary", "internal".
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// An array of domains used for custom name servers. This is only
	// available for Business and Enterprise plans.
	// +kubebuilder:validation:Optional
	VanityNameServers []*string `json:"vanityNameServers,omitempty" tf:"vanity_name_servers,omitempty"`
}

// ZoneSpec defines the desired state of Zone
type ZoneSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ZoneParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZoneInitParameters `json:"initProvider,omitempty"`
}

// ZoneStatus defines the observed state of Zone.
type ZoneStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZoneObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Zone is the Schema for the Zones API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Zone struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.account) || (has(self.initProvider) && has(self.initProvider.account))",message="spec.forProvider.account is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ZoneSpec   `json:"spec"`
	Status ZoneStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneList contains a list of Zones
type ZoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Zone `json:"items"`
}

// Repository type metadata.
var (
	Zone_Kind             = "Zone"
	Zone_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Zone_Kind}.String()
	Zone_KindAPIVersion   = Zone_Kind + "." + CRDGroupVersion.String()
	Zone_GroupVersionKind = CRDGroupVersion.WithKind(Zone_Kind)
)

func init() {
	SchemeBuilder.Register(&Zone{}, &ZoneList{})
}
